# Generated by Django 3.2.8 on 2022-04-07 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=255, verbose_name='telefone'),
        ),
    ]
