# Generated by Django 3.2.8 on 2022-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_auto_20220420_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
